### PR TITLE
BCP-96: Add Glob Patterns Support

### PR DESCRIPTION
**Pull request by JinnyYi**
ref: https://github.com/beyondstorage/beyond-ctl/issues/77

### CODE REVIEW

**Comment by Xuanwo** [comment]
Glob support sounds like can also be used in `mv`, `ls` and `rm`. Maybe our BCP should support them in general? For example:

```
byctl cp *.png example:/
```

**Comment by JinnyYi** [comment]
> Glob support sounds like can also be used in `mv`, `ls` and `rm`. Maybe our BCP should support them in general? 

Yes. I'll update it.

 > `byctl cp *.png example:/`

It looks more friendly then `--exclude` and `--include`. In addition, `--exclude` and `--include` do not support patterns containing directory info, e.g., --include "/usr/*/test/*.jpg".

**Comment by Xuanwo** [comment]
> It looks more friendly then `--exclude` and `--include`. In addition, `--exclude` and `--include` do not support patterns containing directory info, e.g., --include "/usr/fo*/test/*.jpg".

How about supporting `byctl cp *.png example:/` only and leave `exclude` and `include` to implement later?

**Comment by JinnyYi** [comment]
> How about supporting `byctl cp *.png example:/` only and leave `exclude` and `include` to implement later?

I‘ve moved `exclude` and `include` to the `Alternative Way`, does this section need to be removed?

In addition, do we expect to support only * pattern, or do we support the multiple patterns listed in the latest commit?

**Comment by Xuanwo** [comment]
> I‘ve moved `exclude` and `include` to the `Alternative Way`, does this section need to be removed?

LGTM, we don't need to remove them.

 
> In addition, do we expect to support only * pattern, or do we support the multiple patterns listed in the latest commit?

Maybe we can use https://github.com/gobwas/glob.

**Comment by JinnyYi** [comment]
> Maybe we can use https://github.com/gobwas/glob.

Got it. `filepath.Match()` is slightly faster then `gobwas/glob` from my test, but `filepath.Match()` doesn't support `{ }`.

**Comment by Xuanwo** [comment]
> Got it. `filepath.Match()` is slightly faster then `gobwas/glob` from my test, but `filepath.Match()` doesn't support `{ }`.

I think we need to support `**` which `filepath.Match` doesn't support.

**Comment by Xuanwo** [comment]
Mostly LGTM, let's create a tracking issue about this BCP.

**Pull request merged**
